# bb_rt.py — raytraced breakaway (Ballblazer-inspired), milestone 6 (GENERATED by gen_rt.py — edit the generator)
# rt_main(): asm, core 1, never returns until CTRL[EXIT]: game logic, per-frame setup, even rows.
# rt_rows(): asm, called by io_loop on core 0 each frame: odd rows, then returns.
# io_loop(): Viper on core 0 — gamepad -> CTRL, rt_rows, 2x doubling, HUD.
#
# Scene: mode-7 floor with box-filtered checker, Fresnel floor reflections (objects
# mirrored through the floor plane), soft contact shadow, emissive orb with glow and
# floor light, three chrome defenders (ellipsoids) with one reflection bounce, rim and
# stripe, emissive goal posts, analytic edge anti-aliasing. Sky: ringed gas giant and
# stars (in every reflection), translucent arena walls, collision spark bursts.
# Game: start each run carrying the orb at one end of a long field; three defenders
# guard zones and try to ram it loose. GAMEPAD_LEFT/RIGHT strafe. Shoot (GAMEPAD_UP) straight ahead into the
# sliding goal; the reticle marks your heading. A defender
# touching a loose orb is a turnover. All of it runs inside rt_main.
# Colors: PALETTES below (GAMEPAD_DOWN cycles them live).
from dvi_rp2_hstx_frame_sync_v2 import DVI_RP2_HSTX
from gamepadfast import Gamepad
from draw_numberdvi import Draw_number
import colors as rv_colors
import gc, array, _thread, machine, uctypes, framebuf
from math import tan, radians, sqrt
from time import sleep_ms, ticks_ms

SCREEN_W = const(320)
SCREEN_H = const(240)
BYTES_PER_PIXEL = const(2)
RW = const(160)          # render width
RH = const(120)          # render height
FPS_CORE0 = const(0)

machine.freq(246_000_000)
machine.mem32[0x40010058] = 2 << 16   # HSTX CLK / 2
machine.mem32[0x40010054] = 1 << 11   # HSTX CLK use SYS CLK

fb = bytearray(SCREEN_W * SCREEN_H * BYTES_PER_PIXEL)
display = DVI_RP2_HSTX()
display.begin(fb, rv_colors.COLOR_MODE_BGR565, height=SCREEN_H, width=SCREEN_W,
              bytes_per_pixel=BYTES_PER_PIXEL)
draw_num = Draw_number(fb, SCREEN_W, BYTES_PER_PIXEL)
gamepad = Gamepad()

RB0 = bytearray(RW * RH * 2)
RB1 = bytearray(RW * RH * 2)
STARL = bytearray(RW * 60)      # stars, splatted once per frame by rt_main
SPKL = bytearray(RW * RH)       # spark glow, splatted once per frame by rt_main
# Buffers must be in SRAM: HSTX DMA and the renderer both slow badly (tearing) from PSRAM.
# Compiling the large .py on the board fragments SRAM, so run the precompiled bb_rt.mpy.
for _n, _b in (('fb', fb), ('RB0', RB0), ('RB1', RB1), ('STARL', STARL), ('SPKL', SPKL)):
    _ad = uctypes.addressof(_b)
    if _ad and not 0x20000000 <= _ad < 0x20082000:
        print('warning:', _n, 'is outside SRAM at', hex(_ad), '- run bb_rt.mpy instead of bb_rt.py')

# ── CTRL: int32 shared state (byte offsets for asm) ──────────────────────────
C_EXIT     = const(0)    # io_loop -> asm: nonzero = return
C_FRAME    = const(1)    # asm: frames completed
C_CONSUMED = const(2)    # io_loop: last frame count doubled to fb
C_PADX     = const(3)    # -512..512, deadzoned
C_PADY     = const(4)
C_BTN      = const(5)
C_RB0      = const(6)    # render buffer addresses
C_RB1      = const(7)
C_HOLD     = const(8)    # asm: 1 you carry the orb, 0 loose
C_GOALS    = const(9)    # asm: goals scored
C_TURNOVER = const(10)   # asm: runs lost to a defender reaching a loose orb
C_CD_P     = const(11)   # asm: pickup cooldown (frames)
C_SIDE     = const(13)   # asm: loose orb off-screen: -1 left, 1 right, 0 visible/held
C_AIM      = const(14)   # asm: 1 = aim assist locked on the goal
C_SETUP    = const(16)   # asm (core 1): frame n is set up, FP1 is valid
C_HALF     = const(17)   # rt_rows (core 0): odd rows of frame n are done
C_RBCUR    = const(18)   # asm: render buffer for frame n
C_TEX      = const(19)   # address of TEX
C_FP1      = const(20)   # address of FP1
C_SEED     = const(21)   # spark random generator state
C_STARL    = const(23)   # address of the star light layer (160 x 60 bytes)
C_SPKL     = const(24)   # address of the spark light layer (160 x 120 bytes)
CTRL = array.array('i', [0] * 28)
CTRL[C_SEED] = 12345
CTRL[C_HOLD] = 1         # each run starts with the orb
CTRL[C_BTN] = 0xFF       # buttons are active low: nothing pressed
CTRL[C_RB0] = uctypes.addressof(RB0)
CTRL[C_RB1] = uctypes.addressof(RB1)
CTRL[C_STARL] = uctypes.addressof(STARL)
CTRL[C_SPKL] = uctypes.addressof(SPKL)

# ── FP: float32 table — scene, camera, constants, scratch (offsets are generated)
#@FP@
# 16:9 monitor showing the 4:3 picture stretched: pixels are 4/3 wider than tall.
# 1 = widen each pixel's horizontal ray angle by 4/3 (same vertical view, wider
# horizontal view) so circles stay round on that monitor. 0 = square pixels (4:3 display).
WIDE_PIXELS = const(1)
if WIDE_PIXELS:
    FP[O_U0 // 4] *= 4 / 3
    FP[O_DU // 4] *= 4 / 3

# Screen projection for splatted points (stars, sparks): column = x/z * IDU + IU0, row = JV0 - y/z * IDV
FP[O_IDU // 4] = 1 / FP[O_DU // 4]
FP[O_IU0 // 4] = -FP[O_U0 // 4] / FP[O_DU // 4]
FP[O_IDV // 4] = 1 / FP[O_DV // 4]
FP[O_JV0 // 4] = FP[O_V0 // 4] / FP[O_DV // 4]

# Edge anti-aliasing: coverage scale per object from the final pixel footprint.
_du = (FP[O_DU // 4] + FP[O_DV // 4]) / 2
FP[O_KORBF // 4] = 1 / (2 * 0.30 * _du)     # orb radius loose
FP[O_KORBH // 4] = 1 / (2 * 0.15 * _du)     # orb radius while carried
FP[O_KORB // 4] = FP[O_KORBH // 4]
FP[O_KROT // 4] = 1 / (2 * _du * FP[O_IRY // 4])
FP[O_KPOST // 4] = 1 / (2 * sqrt(FP[O_PR2 // 4]) * _du)

# ── Colors and scenery ───────────────────────────────────────────────────────
# RGB 0..1 (above 1 saturates). Edit, add or reorder entries; GAMEPAD_DOWN cycles
# palettes while the game runs. horizon is also the fog color.
#   (sky_top, horizon, tile_a, tile_b, orb_edge, orb_core, chrome_tint, accent, post, gloss,
#    wall, features)
#   accent = rotofoil rim and stripe; gloss = floor reflectivity (1.0 = default mirror strength)
#   features: GIANT | STARS | WALLS (sparks are always on; DRONES needs ND = 1 in gen_rt.py)
GIANT, STARS, WALLS, DRONES = 1, 2, 4, 8
PALETTES = (
    ((0.03, 0.05, 0.22), (0.95, 0.55, 0.40), (0.02, 0.02, 0.05), (0.70, 0.62, 0.70),   # 0 twilight, gas giant
     (1.00, 0.72, 0.30), (1.00, 0.98, 0.85), (0.90, 0.85, 1.00), (0.30, 0.90, 1.00), (1.00, 0.45, 0.08), 0.7,
     (0.30, 0.90, 1.00), GIANT | STARS | WALLS),
    ((0.12, 0.40, 0.95), (0.72, 0.88, 1.00), (0.00, 0.00, 0.00), (0.80, 0.82, 0.86),   # 1 sky blue / black
     (1.00, 0.72, 0.30), (1.00, 0.98, 0.85), (0.85, 0.90, 1.00), (1.00, 0.35, 0.10), (1.00, 0.45, 0.08), 0.45,
     (0.20, 0.90, 1.00), WALLS),
    ((0.02, 0.02, 0.10), (0.42, 0.18, 0.50), (0.04, 0.10, 0.32), (0.62, 0.70, 0.86),   # 2 dusk
     (1.00, 0.72, 0.30), (1.00, 0.98, 0.85), (1.00, 0.55, 0.78), (0.20, 0.90, 1.00), (1.00, 0.45, 0.08), 1.0,
     (1.00, 0.40, 0.90), GIANT | STARS | WALLS),
    ((0.00, 0.00, 0.02), (0.00, 0.30, 0.35), (0.00, 0.00, 0.00), (0.00, 0.35, 0.40),   # 3 night grid
     (1.00, 0.50, 0.10), (1.00, 0.90, 0.60), (0.70, 1.00, 1.00), (1.00, 0.45, 0.00), (0.20, 1.00, 0.90), 1.0,
     (0.20, 1.00, 0.60), STARS | WALLS),
    ((0.08, 0.06, 0.30), (1.00, 0.55, 0.28), (0.10, 0.04, 0.10), (0.90, 0.62, 0.42),   # 4 sunset
     (1.00, 0.85, 0.40), (1.00, 1.00, 0.90), (1.00, 0.75, 0.60), (0.60, 0.30, 1.00), (1.00, 0.90, 0.30), 0.8,
     (1.00, 0.60, 0.20), GIANT | WALLS),
)
PALETTE = const(0)          # palette at power-up
AMBIENT = 0.22              # floor ambient; matches AMB in gen_rt.py

def _pal(p):                # palette -> (FP index, value) pairs, derived terms included
    top, hor, ta, tb, oe, oc, tint, acc, post, gloss, wall, feat = PALETTES[p]
    lit = AMBIENT + (1 - AMBIENT) * FP[O_LX // 4 + 1]
    ta = [c * lit for c in ta]
    tb = [c * lit for c in tb]
    g = [(e + c) / 2 for e, c in zip(oe, oc)]
    out = []
    for o, vals in ((O_TA, ta), (O_TB, tb), (O_DT, [b - a for a, b in zip(ta, tb)]),
                    (O_HOR, hor), (O_DH, [t - h for t, h in zip(top, hor)]),
                    (O_OE, oe), (O_OD, [c - e for c, e in zip(oc, oe)]), (O_OCORE, oc),
                    (O_GLOW, g), (O_OLIGHT, [c * 0.9 for c in g]),
                    (O_TINT, tint), (O_RIM, [c * 0.6 for c in acc]), (O_STRIPE, [c * 1.4 for c in acc]),
                    (O_MREF, [t * (0.5 * (a + b) + h) * 0.6 for t, a, b, h in zip(tint, ta, tb, hor)]),
                    (O_POSTC, post), (O_POSTREF, [c * 0.8 for c in post]),
                    (O_RSIL, [t * h + 0.6 * c for t, h, c in zip(tint, hor, acc)]),
                    (O_FR0, [0.10 * gloss]), (O_FR1, [0.65 * gloss]),
                    (O_WC, wall), (O_FEATF, [float(feat)])):
        for k, x in enumerate(vals):
            out.append((o // 4 + k, x))
    return out

PAL_IDX = array.array('H', [i for i, _ in _pal(0)])
PAL_DATA = tuple(array.array('f', [x for _, x in _pal(p)]) for p in range(len(PALETTES)))
PAL_COUNT = len(PALETTES)
for _j in range(len(PAL_IDX)):
    FP[PAL_IDX[_j]] = PAL_DATA[PALETTE][_j]
FP1 = array.array('f', FP)  # core 0's copy; rt_main refreshes it every frame
CTRL[C_FP1] = uctypes.addressof(FP1)

# ── TEX: spark state, gas-giant band and ring tables, drone sprite frames ───
from math import sin
TEX = array.array('f', [0.0] * TEX_LEN)
for _i in range(64):        # planet bands by latitude
    _lat = _i / 32.0 - 1.0
    _b = 0.5 + 0.5 * sin(_lat * 14.0 + 1.6 * sin(_lat * 5.0))
    for _c, (_x, _y) in enumerate(((0.93, 0.62), (0.72, 0.38), (0.48, 0.28))):
        TEX[TEX_BAND // 4 + _i * 3 + _c] = _x * (1 - _b) + _y * _b
for _i in range(64):        # rings by (r/R)^2: premultiplied colour, alpha
    _r = sqrt(G_RR1 + (_i + 0.5) / G_RK)
    _al = 0.75 * (0.55 + 0.45 * sin(_r * 38.0) * sin(_r * 11.0 + 1.0))
    if abs(_r - 1.85) < 0.06:
        _al = 0.0
    for _c, _x in enumerate((0.95, 0.85, 0.70, 1.0)):
        TEX[TEX_RING // 4 + _i * 4 + _c] = _x * _al
# Fixed star field: NSTAR directions on the upper sky, brightness 0-255 (a few bright ones).
_sd = 20261008
def _rnd():
    global _sd
    _sd = (_sd * 1103515245 + 12345) & 0x7FFFFFFF
    return _sd / 0x7FFFFFFF
from math import cos, asin
for _i in range(NSTAR):
    _az = _rnd() * 6.2832
    _el = asin(0.12 + 0.75 * _rnd())          # roughly uniform over the dome, 7 deg and up
    _br = 60 + 140 * _rnd() ** 2
    if _rnd() < 0.12:
        _br = 230.0
    _o = TEX_STAR // 4 + _i * 4
    TEX[_o] = cos(_el) * sin(_az); TEX[_o + 1] = sin(_el); TEX[_o + 2] = cos(_el) * cos(_az); TEX[_o + 3] = _br
# Spotter drone sprite, 16x8, 4 frames: rotor wide/narrow x lamp red/green
# (green = your heading would score). '.' = transparent, L = lamp.
DRONE_ART = (
    ("cccccc....cccccc", "..cc........cc.."),
    ("...m........m...", "...m........m..."),
    ("...mmmmmmmmmm...", "...mmmmmmmmmm..."),
    ("..mggggggggggm..", "..mggggggggggm.."),
    ("..mgLLLLLLLLgm..", "..mgLLLLLLLLgm.."),
    ("..mggggggggggm..", "..mggggggggggm.."),
    ("...mmmmmmmmmm...", "...mmmmmmmmmm..."),
    (".......ww.......", ".......ww......."),
)
DRONE_PAL = {'c': (0.80, 0.88, 0.95), 'm': (0.22, 0.24, 0.30), 'g': (0.55, 0.58, 0.66),
             'w': (1.00, 0.90, 0.60)}
for _f in range(4):
    _rot = _f & 1
    _lamp = (1.6, 0.15, 0.05) if _f < 2 else (0.15, 1.6, 0.30)
    for _y in range(8):
        _row = DRONE_ART[_y][_rot]
        for _x in range(16):
            _ch = _row[_x]
            _col = _lamp if _ch == 'L' else DRONE_PAL.get(_ch, (-1.0, 0.0, 0.0))
            for _c in range(3):
                TEX[(TEX_DRONE + _f * TEX_FRAME) // 4 + (_y * 16 + _x) * 3 + _c] = _col[_c]
CTRL[C_TEX] = uctypes.addressof(TEX)
# ── Core 0: the whole renderer is one function
